swagger: '2.0'
info:
  title: NSP MCP Connector
  description: MCP Server test implementation for NSP IT support system with basic user information retrieval
  version: 1.0.0
  contact:
    name: NSP-MCP-Connector Project
    url: https://github.com/lulielmo/nsp-mcp-connector
host: your-azure-function.azurewebsites.net
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  functionKey:
    type: apiKey
    name: code
    in: query
    description: Function Key for authentication against Azure Function
security:
  - functionKey: []

paths:
  /mcp:
    post:
      summary: NSP MCP Server - Main endpoint for MCP communication
      description: |
        MCP Server test implementation that exposes basic NSP user information via Microsoft Connector Protocol.
        Test version with single tool for validation.
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      tags:
        - MCP
        - NSP
        - IT Support
      parameters:
        - name: code
          in: query
          required: true
          type: string
          description: Function Key for authentication against Azure Function
      responses:
        '200':
          description: Successful MCP response
          schema:
            $ref: '#/definitions/MCPResponse'
        '400':
          description: Bad Request - Invalid MCP request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized - Invalid Function Key
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error - Server error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /health:
    get:
      summary: Health Check Endpoint
      description: Checks that Azure Function and Hybrid Connection are working
      operationId: HealthCheck
      tags:
        - Health
        - Monitoring
      parameters:
        - name: code
          in: query
          required: true
          type: string
          description: Function Key for authentication
      responses:
        '200':
          description: Service healthy
          schema:
            type: object
            properties:
              status:
                type: string
                example: "healthy"
              service:
                type: string
                example: "nsp-mcp-connector"
              local_api_base:
                type: string
                example: "http://localhost:5000"

definitions:
  MCPRequest:
    type: object
    required:
      - method
    properties:
      method:
        type: string
        enum:
          - tools/list
          - tools/call
        description: MCP method to call
        example: "tools/list"
      params:
        $ref: '#/definitions/MCPParams'
    example:
      method: "tools/list"
      params: {}

  MCPParams:
    type: object
    properties:
      name:
        type: string
        description: Name of the MCP tool to call
        example: "get_my_info"
      arguments:
        type: object
        description: Arguments for the MCP tool
        properties:
          user_email:
            type: string
            description: User's email address
            example: "user@example.com"
        additionalProperties: true

  MCPResponse:
    type: object
    properties:
      result:
        description: MCP response data - can be array (tools/list) or object (tool results)
        additionalProperties: true

  ErrorResponse:
    type: object
    properties:
      error:
        type: string
        description: Error message
        example: "Invalid MCP request"

# MCP Tools that are exposed
x-ms-mcp-tools:
  - name: get_my_info
    description: Get current user information and permissions
    inputSchema:
      type: object
      properties:
        user_email:
          type: string
          description: User's email address
      required:
        - user_email

# Metadata for MCP Server
x-ms-mcp-metadata:
  serverType: "NSP IT Support"
  capabilities:
    - userContext
    - userManagement
  authentication:
    type: "functionKey"
    description: "Function Key via query parameter 'code'"
  transport:
    type: "streamable"
    version: "1.0"
    description: "Streamable MCP transport (recommended)"
  description: |
    NSP MCP Server test implementation with simplified functionality:
    - User information retrieval
    - Basic user context management
    - Hybrid connection to on-premises NSP system