version: '3.8'

services:
  nsp-local-server-prod:
    image: nsp-local-server:latest
    container_name: nsp-local-server-prod
    ports:
      - "5002:5000"  # Map host port 5002 to container port 5000
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nsp-prod-network

networks:
  nsp-prod-network:
    driver: bridge
